### PR TITLE
Add support for Laravel 9

### PR DESCRIPTION
**Pull request by benholmen**
Thanks to Laravel Shift @jasonmccreary for this one - it is a copy of #88 but I'm doing it as a human so I can sign the Contributor License Agreement.

### CODE REVIEW

**Review by alexdevandrepair — APPROVED** [review]

**Review by muglug — APPROVED** [review]

**Comment by alexlungu** [comment]
Could you please get this merged in and tagged as it is currently a blocker for upgrading to laravel 9 if we rely on Vimeo integration? 

I'm sure a lot of people would appreciate it 😇 

Thank you guys 👍

**Comment by benholmen** [comment]
Thank you! 🚀

**Comment by alexlungu** [comment]
@sergiosalvatore thank you for merging this in. Any chance you could also tag the release? using dev-master in production feels a bit risky

**Comment by sergiosalvatore** [comment]
@alexlungu sure thing -- 5.7.0 has been tagged and released.

**Pull request merged**
