### PR TITLE
Added laravel 5.6 support

### PR DESCRIPTION
**Pull request by uapixart**

### CODE REVIEW

**Comment by vinkla** [comment]
@uapixart great work! You'll also need to update PHP to `^7.1.3` and update the `.travis.yml` file.

This closes #28 and #27.

**Comment by uapixart** [comment]
@vinkla 7.0 from .travis.yml already removed

**Comment by uapixart** [comment]
@vinkla what i must do next for receive new version of module?

**Comment by vinkla** [comment]
The Vimeo team need to merge this pull request and release a new version of the package.

**Comment by uapixart** [comment]
OK. Thank you @vinkla!!

**Comment by erunion** [comment]
Awesome, thank you!

Since 4.0.0 doesn't install on Laravel 5.6, I'm going to tag this as 5.0.0.

**Comment by erunion** [comment]
@uapixart I forgot to ask, but can you also sign our CLA? https://developer.vimeo.com/cla

**Comment by uapixart** [comment]
@erunion I agreed to the terms! Thank you!

**Pull request merged**
